#ifndef __SHARED_CONFIG_H__
#define __SHARED_CONFIG_H__

#define SERVER_GREETING "MBSRV1.0"
#define CLIENT_GREETING "PROTO_OK"
enum RequestType {REQ_GAME_CONF, REQ_GAME_MAP, REQ_GAME_FILE, REQ_MOVE, REQ_PUT,
	REQ_REMOTE, REQ_USE, REQ_TAKE, REQ_FINISH};

#define NET_BLOCK 1024

#define LOC_GAME_XML "conf.xml"
#define LOC_GAME_MAP "conf.map"

#endif
